### ISSUE TITLE
Unknown UGI message with head 'b'

### ISSUE THREAD

**Issue by LucasBorboleta** [eclypse-prime/pijersi-rs#28]
Version 1.0.0 replies the UGI message ['b'] after request ['go', 'depth', '2'].
It is a minor and non-blocking bug.

Here attached is a complete UGI sequence : [UGI-minor-bug.txt](https://github.com/user-attachments/files/16507835/UGI-minor-bug.txt)

**Comment by eclypse-prime** [comment]
board.rs line 158
